class TecnologiaRepository {
  List<String> tecnologias() => [
        "Adobe XD",
        "Assembly",
        "C",
        "C#",
        "C++",
        "Clojure",
        "COBOL",
        "Dart",
        "Delphi",
        "Elixir",
        "Erlang",
        "Figma",
        "Flutter",
        "Fortran",
        "Go",
        "Groovy",
        "Haskell",
        "Illustrator",
        "Java",
        "JavaScript",
        "Julia",
        "Kotlin",
        "Lisp",
        "Lua",
        "Matlab",
        "MongoDB",
        "MySQL",
        "NodeJS",
        "Objective-C",
        "Perl",
        "PHP",
        "Photoshop",
        "PowerShell",
        "Python",
        "R",
        "React",
        "Ruby",
        "Rust",
        "Scala",
        "Scratch",
        "Swift",
        "TypeScript",
        "Visual Basic",
      ];
}
